"""定数定義"""

APP_NAME = "SortSnap"
APP_VERSION = "1.0.0"
BUILD_DATE = "2025-10-06"

# ファイル形式
SUPPORTED_FORMATS = [".jpg", ".jpeg", ".png"]

# デフォルト値
DEFAULT_THUMBNAIL_SIZE = 200
MIN_THUMBNAIL_SIZE = 100
MAX_THUMBNAIL_SIZE = 400
THUMBNAIL_SIZE_STEP = 50

DEFAULT_JPG_QUALITY = 95
DEFAULT_RENAME_DIGITS = 3
DEFAULT_RENAME_START = 1

# ログ
MAX_LOG_FILES = 30

# Undo/Redo
MAX_HISTORY = 50

# UI
WINDOW_DEFAULT_SIZE = (1920, 1080)
WINDOW_MIN_SIZE = (1280, 720)

# アニメーション
ANIMATION_CSV_PATH = "animations/animations.csv"
ANIMATION_FRAMES_DIR = "animations/frames"
